### ISSUE TITLE
Create playersByRank method

### ISSUE THREAD

**Issue by ilkeraslan** [ilkeraslan/dota2compose#4]
We should create a `playersByRank()` method inside the `PlayersRepository` which will get players by their rank.

This repository should:
- [ ] Have a method named `playersByRank()` which makes an API call to [this endpoint](https://api.opendota.com/api/playersByRank).
- [ ] This method should return a list of account id's of the players.

**Comment by indyfromoz** [comment]
Hi @ilkeraslan,

Now that I have completed #21, can I work on this?

**Comment by ahmetkca** [comment]
@indyfromoz @ilkeraslan Hi I know it initially assigned to me but I wasn't able to deliver it. Could you give me one more time?

**Comment by ahmetkca** [comment]
`playersByRank` only return account_id. rank_tier and  fh_unavailable. Should it return List of Players by also making additional call to `/players/{account_id}`

**Comment by ilkeraslan** [comment]
> `playersByRank` only return account_id. rank_tier and fh_unavailable. Should it return List of Players by also making additional call to `/players/{account_id}`

Hey @ahmetkca thank you for your interest in the issue. The idea would be that, but I would like to implement is as a separate call. There will be a 3rd method in future which merges these two calls and returns the `Player` instead or returning the `id.

If it's ok with you, you can work on the second call that you are proposing, for which I will create a separate issue. We can assign this one to @indyfromoz so you can both work on similar issues.

Does that sound ok?

**Comment by ilkeraslan** [comment]
Great, assigned this to @indyfromoz
