### ISSUE TITLE
Create Splash Screen

### ISSUE THREAD

**Issue by ilkeraslan** [ilkeraslan/dota2compose#9]
We should create a Splash Screen using the new Splash Screen API. 

The Screen should have:
- [ ] The official DOTA2 logo
- [ ] App title (dota2compose)
- [ ] Background color: choose whatever works the best :grinning: 

Useful documentation: https://developer.android.com/guide/topics/ui/splash-screen

**Comment by V9vek** [comment]
Hi 👋🏻 @ilkeraslan I would like to work on this, if this is open for contribution, please assign it to me.

**Comment by V9vek** [comment]
I was looking at the `New Splash API`, there we cannot set the text in the splash for less than Android 12. So do you want to custom splash screen or with icon only is fine?

**Comment by ilkeraslan** [comment]
> I was looking at the `New Splash API`, there we cannot set the text in the splash for less than Android 12. So do you want to custom splash screen or with icon only is fine?

Thank you for your interest @V9vek , I am assigning this to you. I guess only the logo is fine for now, you can use the asset which I used for app icon that you find in the project. Let me know if you have any questions!

**Comment by V9vek** [comment]
Cool 👍🏻, I will open the PR for the same.

**Comment by V9vek** [comment]
@ilkeraslan I have opened the PR #23
please check it out 😉
